# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: gatsby-practice-app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - run: echo "Setting up NodeJs"
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Instal Dependencies
      run: npm install
    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli
    - name: Build Gatsby App
      run: npm run gatsby build --if-present
    - name: Install Surge
      run: npm install -g surge
    - name: Deploying website
      run: surge public/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }} 
